### ISSUE TITLE
Error `You must set JOHNNY_CONFIG; exiting.`

### ISSUE THREAD

**Issue by def-mycroft** [beancount/johnny#7]
I'm following these steps: 

```
1. Setup the virtual environment: `python3 -m venv venv`
2. Activate it: `source venv/bin/activate`
3. Install the package for local development into the virtual environment: `pip install --editable .`
4. Run the web UI: `export JOHNNY_ROOT=/path/to/johnny/data && ./bin/johnny-web`
5. Visit the web UI at http://localhost:5000
```

when running the 4th line above, I receive message: 

```
You must set JOHNNY_CONFIG; exiting.
```

I assume I need to set up a config file somewhere?

**Comment by blais** [comment]
I just updated the instructions.
See Makefile for the actual commands I run.
Typically, for an update, I do
```
    make update import diff clobber serve
```

I'll explain in more detail at the talk.

The only input now is a single johnny.pbtxt configuration file that lists the inputs and outputs.
It reads and produces a distinct chains.pbtxt file that contains the clusters of transactions (the "chains"), which you can also edit manually, e.g. insert groups, comments, etc. and normalized transactions and positions tables as CSV. That's what the import does. Since the chnages I made several weeks ago, johnny-web only serves those (no import, import is a distinct step).

**Comment by def-mycroft** [comment]
okay, thx, I have that working now.
